# https://github.com/sualeh/build-jpackage/blob/master/.github/workflows/build-jpackage.yml

name: Build Installers

on:
  workflow_dispatch:

jobs:
  build-linux-installer:
    name: Build Installer on Linux
    runs-on: ubuntu-latest
    steps:

      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          mvn package -Ppackage
          jpackage --verbose "@jpackage.cfg" "@jpackage-linux.cfg"
      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          path: distributions/*
          name: linux-installer
          retention-days: 1


  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:

      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          mvn package -Ppackage
          jpackage --verbose "@jpackage.cfg" "@jpackage-windows.cfg"
      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          path: distributions/*
          name: windows-installer
          retention-days: 1


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-installer, build-windows-installer]
    steps:

      # DOWNLOAD INSTALLERS
      - id: download-linux-installer
        name: Download Linux installer
        uses: actions/download-artifact@v2
        with:
          name: linux-installer

      - id: download-windows-installer
        name: Download Windows installer
        uses: actions/download-artifact@v2
        with:
          name: windows-installer

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *
